version: '3'
services:
  frontend:
    image: antoinejaussoin/dacoustie
    # build: . # Use this when testing
    depends_on:
      - db
    ports:
      - '1800:80'
    environment:
      FTP_USER: changeme
      FTP_PASSWORD: changeme
      DB_HOST: db
      DB_USER: dac
      DB_PASSWORD: changeme
      DB_NAME: dacoustie
      SECRET: changeme
    restart: unless-stopped
    volumes:
      - ./images:/var/www/dacoustie/images
      - ./backup:/var/backup
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  db:
    image: mariadb:10.7.1-focal
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: dacoustie
      MYSQL_USER: dac
      MYSQL_PASSWORD: changeme
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 1801:8080
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
