version: '3'
services:
  frontend:
    build: .
    depends_on:
      - db
    ports:
      - '1800:80'
    environment:
      FTP_USER: changeme
      FTP_PASSWORD: changeme
      DB_HOST: db
      DB_USER: dac
      DB_PASSWORD: changeme
      DB_NAME: dacoustie
      SECRET: changeme
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: dacoustie
      MYSQL_USER: dac
      MYSQL_PASSWORD: changeme

  

volumes:
  database:
  pgadmin: