name: 'Beta Build'

on:
  push:
    branches: [https]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Read VERSION
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./VERSION

      - name: Echo VERSION
        run: echo ${{ steps.package.outputs.content }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          file: ./Dockerfile
          context: .
          tags: antoinejaussoin/dacoustie:beta
          platforms: linux/amd64,linux/arm64
          push: true
